#pv.yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  namespace: tsunami
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: path/to/logs

#pvc.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: tsunami
spec:
  volumeName: logs-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
      